/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package book;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/**
 *
 * @author x23145234
 */
public class BookGUI extends javax.swing.JFrame {
    ArrayList<Book>booklist = new ArrayList<>();

    /**
     * Creates new form BookGUI
     */
    public BookGUI() {
        initComponents();
        
        fileTypeLBL.setVisible(false);
        fileTypeTF.setVisible(false);
        isbnLBL.setVisible(false);
        isbnTF.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        exitBTN = new javax.swing.JButton();
        titleLBL = new javax.swing.JLabel();
        titleTF = new javax.swing.JTextField();
        authorTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        isbnTF = new javax.swing.JTextField();
        authorLBL = new javax.swing.JLabel();
        isbnLBL = new javax.swing.JLabel();
        displayBTN = new javax.swing.JButton();
        ebookRB = new javax.swing.JRadioButton();
        bookRB = new javax.swing.JRadioButton();
        fileTypeLBL = new javax.swing.JLabel();
        fileTypeTF = new javax.swing.JTextField();
        saveBTN = new javax.swing.JButton();
        loadBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        titleLBL.setText("TITLE:");

        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        authorLBL.setText("AUTHOR:");

        isbnLBL.setText("ISBN:");

        displayBTN.setText("DISPLAY");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });

        buttonGroup1.add(ebookRB);
        ebookRB.setText("EBOOK");
        ebookRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebookRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(bookRB);
        bookRB.setText("BOOK");
        bookRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRBActionPerformed(evt);
            }
        });

        fileTypeLBL.setText("FILE TYPE:");

        saveBTN.setText("SAVE");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        loadBTN.setText("LOAD");
        loadBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBTNActionPerformed(evt);
            }
        });

        jLabel1.setText("PLEASE SELECT BOOK TYPE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(isbnLBL)
                    .addComponent(authorLBL)
                    .addComponent(fileTypeLBL)
                    .addComponent(titleLBL))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isbnTF)
                    .addComponent(authorTF)
                    .addComponent(titleTF)
                    .addComponent(fileTypeTF))
                .addGap(229, 229, 229))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bookRB)
                                .addGap(59, 59, 59)
                                .addComponent(ebookRB))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(loadBTN)
                        .addGap(60, 60, 60)
                        .addComponent(addBTN)
                        .addGap(40, 40, 40)
                        .addComponent(displayBTN)
                        .addGap(34, 34, 34)
                        .addComponent(saveBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(exitBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookRB)
                    .addComponent(ebookRB))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(authorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(authorLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(isbnTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(isbnLBL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileTypeLBL)
                    .addComponent(fileTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayBTN)
                    .addComponent(saveBTN)
                    .addComponent(addBTN)
                    .addComponent(loadBTN))
                .addGap(36, 36, 36)
                .addComponent(exitBTN)
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        Book books = new Book();
        String author = authorTF.getText();
        books.setAuthor(author);
        String title = titleTF.getText();
        books.setTitle(title);
        String isbn = isbnTF.getText();
          books.setIsbn(isbn);
        eBook Ebook = new eBook();
        String fileType = fileTypeTF.getText();
      
     
        booklist.add(books);
        
        displayTA.setText("Title: " + books.getTitle() + ", Author: " + books.getAuthor() + ", ISBN: " + books.getIsbn());
        
        
    }//GEN-LAST:event_addBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < booklist.size(); i++){
          //get.booklist(i)
           //displayTA.append(e.toString + "\n");
            
            
        }
    }//GEN-LAST:event_displayBTNActionPerformed

    private void ebookRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebookRBActionPerformed
        // TODO add your handling code here:
        isbnLBL.setVisible(false);
        isbnTF.setVisible(false);
           fileTypeTF.setVisible(true);
        fileTypeLBL.setVisible(true);
        
        
    }//GEN-LAST:event_ebookRBActionPerformed

    private void bookRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRBActionPerformed
        // TODO add your handling code here:
        isbnLBL.setVisible(true);
        isbnTF.setVisible(true);
        fileTypeTF.setVisible(false);
        fileTypeLBL.setVisible(false);
    }//GEN-LAST:event_bookRBActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        File f;
        FileOutputStream fs;
        ObjectOutputStream os;
        
        
        
        try{ 
            f = new File("log.dat");
        fs = new FileOutputStream(f);
        os = new ObjectOutputStream(fs);
        os.writeObject(booklist);
        displayTA.setText("Book has been added to the file!");
        os.close();
        
            
        }catch(IOException e){
            displayTA.setText("Error writing file" + e);
            
        }
        
    }//GEN-LAST:event_saveBTNActionPerformed

    private void loadBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBTNActionPerformed
        // TODO add your handling code here:
        File f;
        FileInputStream fs;
        ObjectInputStream os;
        
        try{
            f = new File("log.dat");
            fs = new FileInputStream(f);
            os = new ObjectInputStream(fs);
            
            os.readObject();
            os.close();
            
            
        }catch(IOException e){
            displayTA.setText("Error Reading The File");
            
            
        }catch(ClassNotFoundException c){
            displayTA.setText("Class not found");
            
            
        }
    }//GEN-LAST:event_loadBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel authorLBL;
    private javax.swing.JTextField authorTF;
    private javax.swing.JRadioButton bookRB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton displayBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JRadioButton ebookRB;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel fileTypeLBL;
    private javax.swing.JTextField fileTypeTF;
    private javax.swing.JLabel isbnLBL;
    private javax.swing.JTextField isbnTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadBTN;
    private javax.swing.JButton saveBTN;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JTextField titleTF;
    // End of variables declaration//GEN-END:variables
}
